### ISSUE TITLE
Comment button isn't resolving text

### ISSUE THREAD

**Issue by JakePartusch** [joerter/johnoerter.me#1]
Hey John,

I know that it is a little weird for me to make an issue on your blog, but I didn't think you would mind ;)

Basically the comment button says `PLUGIN_COMMENTS.SUBMIT_COMMENT_BUTTON_TEXT` which doesn't seem quite right to me ;)

**Comment by joerter** [comment]
Cool thanks Jake! Not sure how that happened haha, but now it's fixed! Also thanks for the comment
